### ISSUE TITLE
jedi seems to have changed

### ISSUE THREAD

**Issue by dsblank** [Calysto/metakernel#127]
Travis is no longer happy, and I think the issue is that jedi has rearranged their code so importing it as we do now fails, resulting in no completions for Python,

@blink1073 do you see this?

**Comment by dsblank** [comment]
Here is the Travis fail:

https://travis-ci.org/Calysto/metakernel/jobs/201735451

**Comment by blink1073** [comment]
Jedi 0.10 was released recently, I'll look at this today.

**Comment by dsblank** [comment]
Thanks! Yes, it looks like 0.10 is causing the problems.

**Comment by blink1073** [comment]
The api for interpreter has [changed](https://github.com/davidhalter/jedi/blob/68c6f8dd0329fce5682bb0d3a5e3e8bf6453ef9d/jedi/utils.py#L86), and will require some work to support 0.9 and 0.10 simultaneously.  I pinned the version on Travis to 0.9 for now.  Worst case if someone has 0.10 they won't get completion for python because the import will fail gracefully.
